# Generated by Django 4.0.2 on 2022-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middleinitial', models.CharField(max_length=1)),
                ('unit', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mos', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('heightininches', models.CharField(max_length=2)),
                ('weightinpounds', models.CharField(max_length=3)),
                ('bodyfatpercentage', models.CharField(max_length=2)),
            ],
        ),
    ]
